#!/usr/bin/env python3

import argparse, socket, time, json, select, struct, sys, math, os

BROADCAST = "FFFF"
RECV_WAIT = 0.1
SEND_WAIT = 0.01

class Replica:
    def __init__(self, port, id, others):
        self.port = port
        self.id = id
        self.others = others

        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('localhost', 0))

        print("Replica %s starting up" % self.id, flush=True)
        hello = { "src": self.id, "dst": BROADCAST, "leader": BROADCAST, "type": "hello" }
        self.send(hello)
        print("Sent hello message: %s" % hello, flush=True)

    def send(self, message):
        self.socket.sendto(json.dumps(message).encode('utf-8'), ('localhost', self.port))

    def recv(self) -> dict:
        ready = select.select([self.socket], [], [], RECV_WAIT)[0]
        if self.socket in ready:
            buffer = ''
            while '}' not in buffer:
                encoded_data, addr = self.socket.recvfrom(65535)
                buffer += encoded_data.decode('utf-8')
            return json.loads(buffer)
        else:
            print("NOTHING READY TO READ")

    def run(self):
        while True:
            msg = self.recv()
            print("Received message '%s'" % (msg,), flush=True)

            match msg["type"]:
                case 'get':
                    pass
                case 'put':
                    pass
                case _:
                    print(f"BADDY TYPE: {msg['type']}")
                
            
            

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='run a key-value store')
    parser.add_argument('port', type=int, help="Port number to communicate")
    parser.add_argument('id', type=str, help="ID of this replica")
    parser.add_argument('others', metavar='others', type=str, nargs='+', help="IDs of other replicas")
    args = parser.parse_args()
    replica = Replica(args.port, args.id, args.others)
    replica.run()
